### ISSUE TITLE
Paper revision

### ISSUE THREAD

**Issue by farshidtz** [linksmart/border-gateway#39]
We can discuss the paper revision here.

Link to paper: https://github.com/linksmart/border-gateway/blob/master/paper/paper.md

To keep track, add this issue number `i.e. #39` to future commits.

**Comment by farshidtz** [comment]
Here are my comments:

> Fraunhofer-Institut für Angewandte Informationstechnik FIT

Change to Fraunhofer Institute for Applied Information Technology

> ``Border Gateway``

Why is this wrapped in backquotes? (and twice)

> using an extensible micro services architecture implemented for Node.js.

This is vague. Isn't it better to say implemented in Node.js? I guess it can be extended in other languages as well, so the used micro services architecture is not specific to Node.js.

> Currently the common protocols HTTP, MQTT and WebSocket are supported. 

Reference for this? Why are these common?

> using a simple rule format

Format not described.

Regarding the diagram:
- are we allowed to used those icons? 
- The icon for Websocket app is a shrunk version of proxies and interfaces (those in blue).


Lastly, the [Bibliography](https://github.com/linksmart/border-gateway/blob/master/paper/paper.bib) needs improvements. The citations are incomplete and I don't think the editor names are relevant.

**Comment by farshidtz** [comment]
Also, it may be useful to add some performance metrics.

**Comment by janniswarnat** [comment]
Many thanks for the comments.

Changing institute name to English.

The backquote wrapping was done because the example paper did the same for their title (https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography). Yet they were referring to a Python package... no need to wrap the name of the software per se.

I thought about this phrasing regarding Node.js too. Switching to "Node.js JavaScript" according to the first answer in https://softwareengineering.stackexchange.com/questions/299152/is-node-js-a-framework.

Changing "common" to "widely used".

The rule format is described in the documentation, no need to explain it in the summary.

The icons are from standard AWS sets in draw.io. I could not find any license information, so I guess they are free to use. The icons are arbitrary, so I don´t think it´s an issue that WebSockets icon looks similar to the icon used for the proxies.

Many citation styles rely on an author or editor field, so I´ll keep it that way.

Raphael asked Hareeqi whether we can publish his thesis, then we could add a link. I added a reference to this thesis and some more technical references.

Adding relevant performance metrics would be a lot of work, so I will not include anything for this submission unless the JOSS reviewers suggest it.

**Comment by farshidtz** [comment]
> Changing institute name to English.

"Fraunhofer Institute for Applied Information Technology FIT" is grammatically wrong. Either the FIT should be in parenthesis or removed. The fact that it is used wrongly everywhere doesn't make it correct :). The abbreviation is not a part of the institute name:
https://www.fraunhofer.de/en/institutes/institutes-and-research-establishments-in-germany.html

> The rule format is described in the documentation, no need to explain it in the summary.

Then there should be a citation right where you mention "simple rule".

> The icons are arbitrary, so I don´t think it´s an issue that WebSockets icon looks similar to the icon used for the proxies.

Then I suggest making the websocket icon grayscale, same as the other application icons.

> Many citation styles rely on an author or editor field, so I´ll keep it that way.

The problem is that the editor is not Marc Jentsch. The title of the website is "COMPOSITION - Ecosystem for collaborative manufacturing processes" and the publication year is probably 2016. You may add `urldate` for the retrieval date and `author` as COMPOSITION Consortium. 
```
@online{composition,
    editor = {Marc Jentsch},
    title = {COMPOSITION},
    url = {https://www.composition-project.eu},
    year = 2019
}
```

**Comment by janniswarnat** [comment]
All suggestions incorporated.

**Comment by farshidtz** [comment]
I noticed that [here](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) they use square braces for the citations but you are using curly braces.

**Comment by janniswarnat** [comment]
Not sure what you mean... where do I use curly braces?

If I used square braces to cite entries in paper.bib R Markdown would translate them to regular braces, so the result would be the same.

**Comment by farshidtz** [comment]
Sorry I meant round braces. You use round instead of square. E.g.:
```
MQTT v3.1.1 (@mqtt) and WebSocket (@rfc6455) are supported.
```

**Comment by farshidtz** [comment]
Here are some examples of JOSS publication for software systems (for your reference):
https://joss.theoj.org/papers/093a37e7d698d3350b2d4e564dcfb69b
https://joss.theoj.org/papers/0cacbf19f5822f668e915f788dec1a82
https://joss.theoj.org/papers/54da18fdbf5d8a61fa66df3a21554008

Full list of publications: https://joss.theoj.org/papers/published

**Comment by janniswarnat** [comment]
The square brackets are only used in the "source code" and will be translated to round braces in the paper. See my updated paper version. In this one I also switched back to the default citation style back from ieee-internet-of-things-journal.csl.

Regarding the length I will come up with some more content and discuss it with Raphael also.

**Comment by janniswarnat** [comment]
Added some more content to the summary. I am happy about further suggestions about content / motivation / structure.

**Comment by farshidtz** [comment]
> Added some more content to the summary. I am happy about further suggestions about content / motivation / structure.

It is much better now. 

I made some minor corrections. Sorry, I meant to make a PR, but ended up committing on master by mistake.

> additionally a more fine-grained authorization using a simple rule format (see below) is performed

> Note that fine-grained authorization rules are currently not supported for the WebSocket proxy.

Regarding `fine-grained authorization`, I think BGW doesn't offer object level security on either of the protocols.

**Comment by raphaelahrens** [comment]
> > Note that fine-grained authorization rules are currently not supported for the WebSocket proxy.
> 
> Regarding `fine-grained authorization`, I think BGW doesn't offer object level security on either of the protocols.

What is currently possible with WebSockets as far as I can see it, it's only possible to block them or allow them right?

**Comment by raphaelahrens** [comment]
> These are then authenticated against an OpenID Connect (OIDC) provider [@oidc] and additionally a more fine-grained authorization using a simple rule format (see below) is performed.

I would change this to 

These are authenticated against an OpenID Connect (OIDC) provider [@oidc] and then authorized using the BGW rule format (see below).

Since authentication is not a form of authorization, but the original sentence suggests this. Also you drop the fine-grained part, which sounds a bit to much like snake oil marketing.

Also drop the simple and maybe add easy to write and read.

**Comment by janniswarnat** [comment]
> > > Note that fine-grained authorization rules are currently not supported for the WebSocket proxy.
> 
> What is currently possible with WebSockets as far as I can see it, it's only possible to block them or allow them right?

Yes, authorization is done on connection establishment only and not on a level of individual messages. Made that clear in the paper. 

> 
> > Regarding `fine-grained authorization`, I think BGW doesn't offer object level security on either of the protocols.
> 
> For HTTP and MQTT we are not checking the payload, yes. The question is compared to what?

All uses of "fine-grained" have been removed :-).

**Comment by janniswarnat** [comment]
Many thanks for the suggestions from both of you!

**Comment by janniswarnat** [comment]
Paper has been submitted.
